Repository Team-Code-Monkeys/secret-cocktail-web-app, pull requests merged in 2023-01, with the labels that each got.

#12 Create blank react router page for admin to view list of facilities
  src/adminfacilitydashboard/index.tsx
  src/adminfacilitydashboard/styles.module.css
  src/adminportal/index.tsx
  src/index.tsx
Labels: enhancement

#11 J2TCM-12 Created .csv download button
  src/adminportal/index.tsx
  src/adminportal/styles.module.css
Labels: enhancement

#18 J2TCM-21 update readme.md for incremental v0.1.0
  README.md
  screenshot/mockup.jpg
Labels: documentation

#13 Facility CSV Download for Admins
  package.json
  src/adminfacilitydashboard/index.tsx
  src/adminportal/index.tsx
  src/adminportal/styles.module.css
  src/index.tsx
  src/login/index.tsx
  src/register/index.tsx
  yarn.lock
Labels: enhancement

#17 J2TCM-18 Added Send Survey Button In Admin Facility Dashboard
  src/adminfacilitydashboard/index.tsx
  src/adminfacilitydashboard/styles.module.css
Labels: enhancement

#21 Modal to specify a new facility to contact
  package.json
  src/globalStyles.css
  src/index.tsx
  src/phonesurvey/index.tsx
  src/phonesurvey/styles.module.css
  yarn.lock
Labels: enhancement

#14 Map page support for query parameters
  src/map/index.tsx
Labels: enhancement

#24 Ability for Admin to Upload CSV for Facilities to Contact
  package.json
  src/adminfacilitydashboard/index.tsx
  src/adminfacilitydashboard/styles.module.css
  src/adminportal/index.tsx
  src/adminportal/styles.module.css
  src/facility/index.tsx
  src/phonesurvey/index.tsx
  src/phonesurvey/styles.module.css
  yarn.lock
Labels: enhancement

#25 Sprint 1 Features
  README.md
  package.json
  screenshot/mockup.jpg
  src/adminfacilitydashboard/index.tsx
  src/adminfacilitydashboard/styles.module.css
  src/adminportal/index.tsx
  src/adminportal/styles.module.css
  src/facility/index.tsx
  src/facility/styles.module.css
  src/globalStyles.css
  src/index.css
  src/index.tsx
  src/landing/index.tsx
  src/login/index.tsx
  src/login/styles.module.css
  src/map/index.tsx
  src/phonesurvey/index.tsx
  src/phonesurvey/styles.module.css
  src/register/index.tsx
  src/register/styles.module.css
  yarn.lock
Labels: bug, documentation, enhancement
